name: Generate code coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install
      run: npm install
    - name: Run tests
      run: npm test -- --collectCoverage
    - name: Report coverage
      run: npm install codecov
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
